apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloud.fullname" . }}
data:
  config.yaml: |-
    title: cloud
    releaseEnv: local
    version: "latest"
    server:
      local:
        cloud:
          port: 80
          readTimeout: 60
          writeTimeout: 60
          runMode: debug
        redis:
          host: redis
          port: 6379