title: cloud
version: "1.0"
runMode: debug
web:
  port: 81
  readTimeout:  60
  writeTimeout: 60

mysql:
  dbType: mysql
  username: root
  host: "localhost:3306"
  password: 123456
  dbName: cloud
  charset: utf8mb4
  parseTime: true
  maxIdleConnections: 10
  maxOpenConnections: 30
mongodb:
  address: localhost:27017
  user: root
  password: 123456
  database: admin