kind: Service
apiVersion: v1
metadata:
  name: prometheus-svc
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: prometheus-server
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 9090
