title = "container cloud"
env = "local"
port = "8080"
version = "1.0"
[server]
    [server.local]
        [server.local.mysql]
        ip = "47.99.241.217"
        port = 3333
        user = "root"
        password = "D4LSD4LSPWO="
        database = "cloud"


