title: "container cloud"
env: "local"
port: "80"
version: "1.0"
server:
  local:
    mysql:
      ip: xisheng.mysql.com
      port: "32404"
      user: "root"
      password: "123456"
      database: "cloud"


