basePath: /api
definitions:
  app.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: object
    type: object
  images.Image:
    properties:
      name:
        default: nginx
        type: string
      version:
        default: latest
        type: string
    type: object
  images.Local:
    properties:
      path:
        default: /data/images
        type: string
    type: object
  images.Pull:
    properties:
      local:
        $ref: '#/definitions/images.Local'
        type: object
      registry:
        $ref: '#/definitions/images.Registry'
        type: object
      remoteHost:
        $ref: '#/definitions/images.RemoteHost'
        type: object
      source:
        $ref: '#/definitions/images.Repo'
        type: object
      type:
        default: local
        type: string
    type: object
  images.Registry:
    properties:
      address:
        type: string
    type: object
  images.RemoteHost:
    properties:
      ip:
        type: string
      password:
        type: string
      port:
        default: 22
        type: integer
      user:
        default: root
        type: string
    type: object
  images.Repo:
    properties:
      addr:
        default: docker.io
        type: string
      images:
        items:
          $ref: '#/definitions/images.Image'
        type: array
      org:
        default: library
        type: string
      password:
        type: string
      user:
        type: string
    type: object
  kubernetes.JoinNodes:
    properties:
      controllerNodes:
        items:
          $ref: '#/definitions/models.Host'
        type: array
      master:
        $ref: '#/definitions/models.Host'
        type: object
      workNodes:
        items:
          $ref: '#/definitions/models.Host'
        type: array
    type: object
  kubernetes.Upgrade:
    properties:
      dryRun:
        type: boolean
      nodes:
        items:
          $ref: '#/definitions/models.Host'
        type: array
      version:
        type: string
    type: object
  models.Cluster:
    properties:
      controlPlaneEndpoint:
        type: string
      id:
        type: string
      master:
        items:
          $ref: '#/definitions/models.Host'
        type: array
      name:
        default: test
        type: string
      networkPlug:
        default: cilium
        type: string
      podCidr:
        default: 10.244.0.0/16
        type: string
      registry:
        default: registry.aliyuncs.com/google_containers
        type: string
      serviceCidr:
        default: 10.96.0.0/16
        type: string
      version:
        default: 1.22.15
        type: string
      workNodes:
        items:
          $ref: '#/definitions/models.Host'
        type: array
    required:
    - controlPlaneEndpoint
    - master
    - name
    type: object
  models.Host:
    properties:
      ip:
        type: string
      password:
        type: string
      port:
        default: 22
        type: integer
      user:
        default: root
        type: string
    type: object
  proxy.Install:
    properties:
      commonName:
        default: test.hello.com
        type: string
      externalPort:
        default: 20001
        description: used for nginx tls， listen to proxy
        type: integer
      ip:
        type: string
      password:
        type: string
      port:
        default: 22
        type: integer
      proxyPort:
        default: 20000
        type: integer
      user:
        default: root
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license: {}
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "2.0"
paths:
  /v1/cluster:
    get:
      consumes:
      - application/json
      description: list cluster
      parameters:
      - description: page number, optional
        in: query
        name: page
        type: integer
      - description: page size, optional
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: list cluster
      tags:
      - k8s cluster
    post:
      consumes:
      - application/json
      description: install cluster master
      parameters:
      - description: install cluster
        in: body
        name: cluster
        required: true
        schema:
          $ref: '#/definitions/models.Cluster'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/app.Response'
      summary: install cluster
      tags:
      - k8s cluster
  /v1/cluster/nodes:
    post:
      consumes:
      - application/json
      description: install k8s nodes
      parameters:
      - description: install cluster slave
        in: body
        name: cluster
        required: true
        schema:
          $ref: '#/definitions/kubernetes.JoinNodes'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/app.Response'
      summary: install cluster nodes
      tags:
      - k8s cluster
  /v1/cluster/upgrade:
    post:
      consumes:
      - application/json
      description: install cluster slave
      parameters:
      - description: k8s all nodes
        in: body
        name: upgrade
        required: true
        schema:
          $ref: '#/definitions/kubernetes.Upgrade'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/app.Response'
      summary: upgrade k8s
      tags:
      - k8s cluster
  /v1/images/info:
    get:
      consumes:
      - application/json
      description: image pull info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: image
      tags:
      - image
  /v1/images/pull:
    post:
      consumes:
      - application/json
      description: image push to oss
      parameters:
      - description: pull Image, then push to OSS
        in: body
        name: cluster
        required: true
        schema:
          $ref: '#/definitions/images.Pull'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/app.Response'
      summary: image push to oss
      tags:
      - image
  /v1/proxy:
    post:
      consumes:
      - application/json
      description: install proxy
      parameters:
      - description: install proxy
        in: body
        name: cluster
        required: true
        schema:
          $ref: '#/definitions/proxy.Install'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/app.Response'
      summary: install proxy
      tags:
      - proxy
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
