basePath: /api
definitions:
  app.Response:
    properties:
      data:
        type: object
      eventCode:
        type: integer
      resMsg:
        type: object
    type: object
  cluster.InstallSlave:
    properties:
      dryRun:
        type: boolean
      master:
        $ref: '#/definitions/models.Host'
        type: object
      nodes:
        items:
          $ref: '#/definitions/models.Host'
        type: array
      version:
        type: string
    type: object
  images.Image:
    properties:
      name:
        type: string
      version:
        type: string
    type: object
  images.Pull:
    properties:
      source:
        $ref: '#/definitions/images.Repo'
        type: object
    type: object
  images.Repo:
    properties:
      addr:
        type: string
      images:
        items:
          $ref: '#/definitions/images.Image'
        type: array
      org:
        type: string
      password:
        type: string
      user:
        type: string
    type: object
  kubernetes.Upgrade:
    properties:
      dryRun:
        type: boolean
      nodes:
        items:
          $ref: '#/definitions/models.Host'
        type: array
      version:
        type: string
    type: object
  models.Host:
    properties:
      ip:
        type: string
      password:
        type: string
      port:
        default: 22
        type: integer
      user:
        default: root
        type: string
    type: object
  models.Kubernetes:
    properties:
      backendMasters:
        items:
          $ref: '#/definitions/models.Host'
        type: array
      controlPlaneEndpoint:
        type: string
      name:
        default: test
        type: string
      networkPlug:
        default: cilium
        type: string
      podCidr:
        default: 10.244.0.0/16
        type: string
      primaryMaster:
        $ref: '#/definitions/models.Host'
        type: object
      registry:
        default: registry.aliyuncs.com/google_containers
        description: registry.aliyuncs.com/google_containers， k8s.gcr.io
        type: string
      serviceCidr:
        default: 10.96.0.0/16
        type: string
      version:
        default: 1.21.0
        type: string
    required:
    - controlPlaneEndpoint
    - name
    - primaryMaster
    type: object
  ossutil.AliOssHelper:
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license: {}
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "2.0"
paths:
  /v1/cluster/masters:
    post:
      consumes:
      - application/json
      description: install cluster master
      parameters:
      - description: install cluster master
        in: body
        name: cluster
        required: true
        schema:
          $ref: '#/definitions/models.Kubernetes'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/app.Response'
      summary: install cluster
      tags:
      - install cluster master
  /v1/cluster/slaves:
    post:
      consumes:
      - application/json
      description: install cluster slave
      parameters:
      - description: install cluster slave
        in: body
        name: cluster
        required: true
        schema:
          $ref: '#/definitions/cluster.InstallSlave'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/app.Response'
      summary: install cluster slave
      tags:
      - install cluster slave
  /v1/cluster/upgrade:
    post:
      consumes:
      - application/json
      description: install cluster slave
      parameters:
      - description: k8s all nodes
        in: body
        name: upgrade
        required: true
        schema:
          $ref: '#/definitions/kubernetes.Upgrade'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/app.Response'
      summary: upgrade k8s
      tags:
      - upgrade
  /v1/images/info:
    get:
      consumes:
      - application/json
      description: image pull info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: image
      tags:
      - image
  /v1/images/pull:
    post:
      consumes:
      - application/json
      description: image push to oss
      parameters:
      - description: pull Image, then push to OSS
        in: body
        name: cluster
        required: true
        schema:
          $ref: '#/definitions/images.Pull'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/app.Response'
      summary: image push to oss
      tags:
      - image
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
