basePath: /api
definitions:
  app.Response:
    properties:
      data:
        type: object
      eventCode:
        type: integer
      resMsg:
        type: object
    type: object
  cluster.Host:
    properties:
      ip:
        type: string
      password:
        type: string
      port:
        default: 22
        type: integer
      user:
        default: root
        type: string
    type: object
  cluster.InstallSlave:
    properties:
      dryRun:
        type: boolean
      master:
        $ref: '#/definitions/models.Host'
        type: object
      nodes:
        items:
          $ref: '#/definitions/models.Host'
        type: array
      version:
        type: string
    type: object
  cluster.clusterParam:
    properties:
      controlPlaneEndpoint:
        type: string
      dryRun:
        type: boolean
      master:
        items:
          $ref: '#/definitions/cluster.Host'
        type: array
      name:
        default: test
        type: string
      networkPlug:
        default: cilium
        type: string
      podCidr:
        default: 10.244.0.0/16
        type: string
      registry:
        default: registry.aliyuncs.com/google_containers
        description: registry.aliyuncs.com/google_containers， k8s.gcr.io
        type: string
      serviceCidr:
        default: 10.96.0.0/16
        type: string
      slaveNode:
        items:
          $ref: '#/definitions/cluster.Host'
        type: array
      version:
        default: 1.22.15
        type: string
    required:
    - controlPlaneEndpoint
    - master
    - name
    type: object
  kubernetes.Upgrade:
    properties:
      dryRun:
        type: boolean
      nodes:
        items:
          $ref: '#/definitions/models.Host'
        type: array
      version:
        type: string
    type: object
  models.Host:
    properties:
      ip:
        type: string
      password:
        type: string
      port:
        default: 22
        type: integer
      user:
        default: root
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license: {}
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "2.0"
paths:
  /v1/cluster:
    get:
      consumes:
      - application/json
      description: list cluster
      parameters:
      - description: page number, optional
        in: query
        name: page
        type: integer
      - description: page size, optional
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: list cluster
      tags:
      - k8s cluster
    post:
      consumes:
      - application/json
      description: install cluster master
      parameters:
      - description: install cluster
        in: body
        name: cluster
        required: true
        schema:
          $ref: '#/definitions/cluster.clusterParam'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/app.Response'
      summary: install cluster
      tags:
      - k8s cluster
  /v1/cluster/slaves:
    post:
      consumes:
      - application/json
      description: install cluster slave
      parameters:
      - description: install cluster slave
        in: body
        name: cluster
        required: true
        schema:
          $ref: '#/definitions/cluster.InstallSlave'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/app.Response'
      summary: install cluster slave
      tags:
      - k8s cluster
  /v1/cluster/upgrade:
    post:
      consumes:
      - application/json
      description: install cluster slave
      parameters:
      - description: k8s all nodes
        in: body
        name: upgrade
        required: true
        schema:
          $ref: '#/definitions/kubernetes.Upgrade'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/app.Response'
      summary: upgrade k8s
      tags:
      - k8s cluster
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
